### PR TITLE
[chore] runs native classes codemod for apps/services

### PR DESCRIPTION
**Pull request by gabrielcsapo**
A continuation of #2227 that runs the native classes codemod against app/services

The following need mixins migrated before we convert

* app/services/dropdown.js
* app/services/settings.js

Please include a description of your change & check your PR against this list, thanks!

- [x] There's a clear use-case for this code change
- [x] Commit message has a short title & references relevant issues
- [x] The build will pass (run `ember test` from the repo root - will be `core/client` if working from the submodule in Ghost).

More info can be found by clicking the "guidelines for contributing" link above.

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
I am going to work on converting the mixins to es6 classes once we merge these so we can simply finish the native classes codemod.

**Comment by kevinansfield** [comment]
> The following need mixins migrated before we convert
>
> app/services/dropdown.js
> app/services/settings.js

Is there something specific about mixin use in those services that failed the codemod? The same mixins used in `settings.js` for example are also used in `custom-views.js` and `config.js`.

**Comment by gabrielcsapo** [comment]
yeah I am digging into that @kevinansfield, some tests failed.

**Comment by gabrielcsapo** [comment]
custom-view and settings weren't converted either

**Comment by kevinansfield** [comment]
Hmm. I just ran the codemod locally and I can't see any issues with the `dropdown` and `settings` migrations, all tests are passing.

`custom-views` didn't convert I think because it errored out because the actual service there is already a native class, it's the `CustomView` object in that file that's not yet converted.

**Comment by kevinansfield** [comment]
`whats-new` and `unsplash` don't convert for me but I don't get any related errors in the codemod output, they are just added to the "unmodified" list 🤔

**Comment by gabrielcsapo** [comment]
Hmm...odd let me just run the codemod and push the contents of that.

Also we ran https://github.com/lennyburdette/ember-action-codemods to some degree of success, might be a good next codemod to get us that much closer to octane.

**Comment by gabrielcsapo** [comment]
I reran from origin/main

**Comment by gabrielcsapo** [comment]
Seems good to go @kevinansfield

**Comment by kevinansfield** [comment]
Ooh, [ember-action-codemods](https://github.com/lennyburdette/ember-action-codemods) does sound like a decent next step.

Merging this one now. Thanks!

So we can track the overall Octane upgrade and potentially get more help where needed, would you mind opening an issue on https://github.com/TryGhost/Ghost/issues with a rough todo list of steps?

**Comment by gabrielcsapo** [comment]
Yes I will add that now! Good idea to keep track of the stages. There is a tool called checkup I can run locally that will track our octane migration. I will add all of that to the ticket.

**Comment by gabrielcsapo** [comment]
I created the issue here https://github.com/TryGhost/Ghost/issues/14101, going to update it over the course of the next hour. So it will look like nothing is there most likely when you view it.

**Pull request merged**
