### PR TITLE
[chore] runs native classes codemod for app/adapters

### PR DESCRIPTION
**Pull request by gabrielcsapo**
A continuation of https://github.com/TryGhost/Admin/pull/2227 that runs the native classes codemod against app/adapters

Please include a description of your change & check your PR against this list, thanks!

- [x] There's a clear use-case for this code change
- [x] Commit message has a short title & references relevant issues
- [x] The build will pass (run `ember test` from the repo root - will be `core/client` if working from the submodule in Ghost).

More info can be found by clicking the "guidelines for contributing" link above.

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
app/adapters/label.js needs to be investigated more. The mixin it is using needs to be migrated to an es6 class us to convert it.

**Comment by gabrielcsapo** [comment]
Are these okay to merge @kevinansfield

**Comment by kevinansfield** [comment]
@gabrielcsapo any idea why it was only the `label` adapter from the multiple ones that use the `SlugUrl` mixin that needed to be rolled back?

**Comment by gabrielcsapo** [comment]
That's a good question, it failed due to a validation error that was occurring when updating the url. I am going to look at the tag tests to see if those have enough coverage.

**Comment by gabrielcsapo** [comment]
@kevinansfield I migrate the slug-url mixin to a utility and made sure the code paths work as expected.

There was never an issue. Locally I was running against the TryGhost/Ghost cli setup and also the local test environment. Seems like I didn't link that one time. If you can see the commits below, the first commit passed without any issue.

Screen Shot 2022-02-02 at 8 36 23 AM

**Comment by gabrielcsapo** [comment]
Fixed lint failure 

```
lib/koenig-editor/addon/components/koenig-card-email.hbs
  1:0  error  'card' is defined but never used  no-unused-block-params
```

**Comment by kevinansfield** [comment]
> I migrate the slug-url mixin to a utility

Nice, that's exactly the fix I was thinking when I saw that mixin earlier 🙌 

> Fixed lint failure

I was surprised that failure popped up. If a template file is edited does that invalidate all of the existing todo's for that file? If so we likely want to disable template linting in CI until we can really pull the number of todo's down.

Otherwise, all looks good though 🎉 Merging now

**Comment by gabrielcsapo** [comment]
https://github.com/TryGhost/Ghost/issues/14101

**Pull request merged**
