### PR TITLE
[chore] adds ember-template-lint and fixes all fixable issues

### PR DESCRIPTION
**Pull request by gabrielcsapo**
Got some code for us? Awesome 🎊!

Screen Shot 2022-02-01 at 9 17 05 PM

Screen Shot 2022-02-01 at 9 15 40 PM

This will help with the octane migration and you can still run the lint rules even when they are todos. (Checkout the docs at https://github.com/ember-template-lint/ember-template-lint/blob/158b1196676489b4bfc01f851b46d3aecd2b314e/docs/todos.md) The good news is any new code will be checked against the recommended config.

I fixed all the auto fixable things we could get in this PR as well.

Please include a description of your change & check your PR against this list, thanks!

- [x] There's a clear use-case for this code change
- [x] Commit message has a short title & references relevant issues
- [x] The build will pass (run `ember test` from the repo root - will be `core/client` if working from the submodule in Ghost).

More info can be found by clicking the "guidelines for contributing" link above.

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
I can fix the merge conflict @kevinansfield

**Comment by gabrielcsapo** [comment]
Since the last time I ran this, 4 errors have been introduced into main.

```
app/components/gh-membership-products-alpha.hbs
  28:51  error  'productIdx' is defined but never used  no-unused-block-params

app/components/modal-portal-settings.hbs
  86:38  error  Ambiguous path 'showPortalPrices' is not allowed. Use '@showPortalPrices' if it is a named argument or 'this.showPortalPrices' if it is a property on 'this'. If it is a helper or component that has no arguments, you must either convert it to an angle bracket invocation or manually add it to the 'no-implicit-this' rule configuration, e.g. 'no-implicit-this': { allow: ['showPortalPrices'] }.  no-implicit-this
  114:38  error  Ambiguous path 'showPortalPrices' is not allowed. Use '@showPortalPrices' if it is a named argument or 'this.showPortalPrices' if it is a property on 'this'. If it is a helper or component that has no arguments, you must either convert it to an angle bracket invocation or manually add it to the 'no-implicit-this' rule configuration, e.g. 'no-implicit-this': { allow: ['showPortalPrices'] }.  no-implicit-this
  10:134  error  Interaction added to non-interactive element  no-invalid-interactive
```

**Comment by gabrielcsapo** [comment]
@kevinansfield rebased and updated the todos for the existing violations

**Comment by gabrielcsapo** [comment]
Just a breakdown of the existing violations:

no-action: 849
no-invalid-interactive: 66
no-inline-styles: 114
no-implicit-this: 83 (There is a codemod for this and it is really good)
no-passed-in-event-handlers: 111
require-valid-alt-text: 38
no-down-event-binding: 32
require-input-label: 31
style-concatenation: 12

**Comment by kevinansfield** [comment]
> no-implicit-this: 83 (There is a codemod for this and it is really good)

I did run that a few days ago, I'm surprised the number is as high as it is 🤔 

Anyhow, thanks again! I'll get this merged before things diverge too much

**Comment by gabrielcsapo** [comment]
https://github.com/TryGhost/Ghost/issues/14101

**Pull request merged**
