### PR TITLE
🐛 Fixed markdown card lacking superscripts & subscripts.

### PR DESCRIPTION
**Pull request by sbeinlich**
refs/closes [Ghost/#12219](https://github.com/TryGhost/Ghost/issues/12219)
Currently, Koenig markdown editor does not support subscripts or
superscript syntax.

Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!

- [X] There's a clear use-case for this code change
- [X] Commit message has a short title & references relevant issues
- [X] The build will pass (run `ember test` from the repo root - will be `core/client` if working from the submodule in Ghost).

More info can be found by clicking the "guidelines for contributing" link above.

### CODE REVIEW

**Comment by sbeinlich** [comment]
Before:
markdown_sub_before

After:
markdown_sub_after

**Comment by sbeinlich** [comment]
I noticed that `Ghost/core/client/tests/unit/components/gh-post-settings-menu-test.js` seemed to contain an old unit test for the markdown editor (line 213). Please let me know if there needs to be any additional testing/QA added for this commit aside from included gifs. I am assuming that it's not necessary to test the markdown engine itself as we're using `markdown-it` for that, and I added plugins. But happy to help wherever needed!

**Comment by ErisDS** [comment]
@sbeinlich Thank you for this PR! I apologise for the delay but this is on my list to review ASAP.

**Comment by krooonal** [comment]
This is not working as of 28 Jan 2022. Can you please reinvestigate?

**Comment by sbeinlich** [comment]
Thanks for taking a look @ErisDS !

**Comment by ErisDS** [comment]
IMO this can be merged (and should have been a long time go, I am so sorry) - the same syntax works just fine when you're typing in the WYSIWYG editor, but doesn't work in the markdown editor, which is unexpected. I had totally missed that this discrepancy existed and thought this PR just added to the markdown card. Sorry again.

**Comment by ErisDS** [comment]
@sbeinlich Thank you so much for the PR, and sorry again for missing that this was a bug. It is merged now and should be in the next minor release of Ghost.

**Pull request merged**
