### PR TITLE
[WIP] Updated subscription event handling

### PR DESCRIPTION
**Pull request by allouis**
@moreofmorris Here's some scaffolded changes for the updated subscription event types

### CODE REVIEW

**Comment by moreofmorris** [comment]
It's a little difficult to test all the event types locally with any "real" data to test all icons — we usually something like Rediverse for that to do a proper test. But one thing I'm noticing is that since you're changing this: `event.data.from_plan` and `event.data.to_plan` in `getAction()`, do we need to do the same in `getIcon()` in the same file as that still seems to reference those?

**Comment by moreofmorris** [comment]
It's a little difficult to test all the event types locally with any "real" data to test all icons — we usually something like Rediverse for that to do a proper test. But one thing I'm noticing is that since you're changing this: `event.data.from_plan` and `event.data.to_plan` in `getAction()`, do we need to do the same in `getIcon()` in the same file as that still seems to reference those?

**Comment by allouis** [comment]
Yeah good shout - I think we do wanna update `getIcon` to show the cancelled icon when the type is `'canceled'`!

**Comment by moreofmorris** [comment]
All good now @allouis, feel free to merge 👍

**Pull request merged**
