### PR TITLE
Added missing schedule events to webhook dropdown

### PR DESCRIPTION
**Pull request by tatsuya-ogawa**
refs https://github.com/TryGhost/Ghost/blob/main/core/server/services/webhooks/listen.js#L18

- update AVAILABLE_EVENTS to latest ghost webhooks.

Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!

- [ ] There's a clear use-case for this code change
- [ ] Commit message has a short title & references relevant issues
- [ ] The build will pass (run `ember test` from the repo root - will be `core/client` if working from the submodule in Ghost).

More info can be found by clicking the "guidelines for contributing" link above.

### CODE REVIEW

**Comment by ErisDS** [comment]
Really sorry that this was just ignored. I am unsure about what the use case for these events is, and not sure they should be in the available events list in the first place 🤔 

Going to close for now as we're about to move the code in this repo into a monorepo. 

If you're still keen, please reopen the PR and explain the use case (it's one of the requests in our PR todo list shown above)

cc @naz I'm not sure why we have webhooks for the scheduled state - do you know? 🤔

**Comment by tatsuya-ogawa** [comment]
@ErisDS 
Thank you for your comment.
My use case is to handle scheduled event on other platform(like zapier, aws lambda, etc...) for later task.

In our environment , ghost content is deployed by JAMStack, and ghost server is not running when it is not writing time.
So we cant use ghost's internal cron task, and external elastic job scheduler is needed.

**Comment by naz** [comment]
The event was added way back in 2019 as a part of https://github.com/TryGhost/Ghost/issues/10461. I do not recall and could not find any concrete references behind the "why?"

**Comment by naz** [comment]
Just remembered we do have support for these events in [Ghost-Zapier integration triggers](https://github.com/TryGhost/Zapier/commit/3f8d56a6a1ebf68baa39a232c6665bf492e44b83).

**Comment by ErisDS** [comment]
Ok thanks for the update @naz, have reopened and merged. Thanks for the PR @tatsuya-ogawa 😄

**Pull request merged**
