### PR TITLE
Improved application loading state

### PR DESCRIPTION
**Pull request by JohnONolan**
Ghost-Admin loading state currently feels really jerky, so made a 5 minute update which I think makes it feel a lot smoother on first load:

Before:
image

After:
image

Before:
load-before

After:
load-after

### CODE REVIEW

**Comment by kevinansfield** [comment]
@JohnONolan do we care about the loading but when not logged in/set up state? That will be more janky after this change because there will be a sidebar that then disappears

**Comment by JohnONolan** [comment]
I forgot about this PR 😬 

@kevinansfield can you think of any reasonable way, with media queries or otherwise, to serve slightly adjusted styles for this on login/signup?

**Comment by kevinansfield** [comment]
The only route I can think of is to change the `/ghost/` endpoint that renders the index.html so that it's aware of the authentication cookie and can modify the served html for logged-in/out states.

**Comment by JohnONolan** [comment]
@ErisDS Any reasonable way for Ghost inject a `<body>` class everywhere based on route? Pretty sure I could CSS it if I could have access to things like `.gh-admin-auth` (login/signup/passreset) / `.gh-admin-setup` (install/setup ghost)

**Comment by ErisDS** [comment]
Closing this as we are prepping to move admin into the monorepo.

**Pull request closed without merging**
