### PR TITLE
[chore] run ember-action-codemods

### PR DESCRIPTION
**Pull request by gabrielcsapo**
Runs the ember-action-codemod as a required in https://github.com/TryGhost/Ghost/issues/14101.

Please include a description of your change & check your PR against this list, thanks!

- [x] There's a clear use-case for this code change
- [x] Commit message has a short title & references relevant issues
- [x] The build will pass (run `ember test` from the repo root - will be `core/client` if working from the submodule in Ghost).

More info can be found by clicking the "guidelines for contributing" link above.

### CODE REVIEW

**Comment by kevinansfield** [comment]
@gabrielcsapo I'm seeing a number of errors from this where the template is being updated from `{{action "x"}}` to `{{on "click" this.x}}` but the related component file has not been transformed to a native class resulting in errors from still using the `actions: {}` hash.

What would be your preferred approach here? Update the previously missed components to native classes first or fix these specific errors by switching to `action(function () {})` where needed?

**Comment by kevinansfield** [comment]
Realised the none of the Koenig-editor in-repo-addon components had been converted to native classes yet so just did that on main and merged in. Reduces the number of EmberObject components left but there's still a considerable number that will fail if this codemod switches actions to `this.*`

```
❯ grep -rL "@classic\|default class" app/components/**/*.js
app/components/gh-basic-dropdown.js
app/components/gh-benefit-item.js
app/components/gh-file-uploader.js
app/components/gh-fullscreen-modal.js
app/components/gh-image-uploader.js
app/components/gh-members-chart.js
app/components/gh-members-payments-setting.js
app/components/gh-navitem.js
app/components/gh-profile-image.js
app/components/gh-psm-authors-input.js
app/components/gh-publishmenu.js
app/components/gh-skip-link.js
app/components/gh-tag-settings-form.js
app/components/gh-task-button.js
app/components/gh-token-input/select-multiple.js
app/components/gh-unsplash-photo.js
app/components/gh-unsplash.js

❯ grep -rL "@classic\|default class" lib/koenig-editor/addon/components/**/*.js
lib/koenig-editor/addon/components/koenig-alt-input.js
lib/koenig-editor/addon/components/koenig-card-image.js
lib/koenig-editor/addon/components/koenig-editor.js
lib/koenig-editor/addon/components/koenig-toolbar.js
```

**Comment by gabrielcsapo** [comment]
Hey @kevinansfield, just got back from vacation I will look at making CI green tomorrow!

**Comment by gabrielcsapo** [comment]
I manually update the koenig editor files in this branch and in https://github.com/TryGhost/Admin/pull/2251.

**Comment by gabrielcsapo** [comment]
another update https://github.com/TryGhost/Admin/pull/2253

**Comment by kevinansfield** [comment]
Hey @gabrielcsapo 👋 Thanks for all the work you put into this. Unfortunately due to the length of time the PR has been open it's become quite out of sync with the current code and we can't move PRs across easily when moving this repo into our monorepo so I'll need to close it.

We're still very much wanting to push everything to latest Ember patterns but I think with the size of the app it will be better to have smaller, targeted updates instead of trying to migrate the whole codebase with a codemod at one time, otherwise we end up in a situation with lots of fixes and reviews to make before we can merge.

Thanks again for your help and input in moving the Octane upgrade forwards 😊.

**Pull request closed without merging**
